- hosts: localhost
  tasks:
    - name: Get some host from the nagios configs
      nagioscfg: 
        hostname: "mytesthost"
        configpath: "/usr/local/nagios/etc/nagios.cfg"
      register: result

    - debug: var=result
